### ISSUE TITLE
reading output

### ISSUE THREAD

**Issue by farsonic** [oxan/esphome-stream-server#2]
I've connected my vBUS2TTY circuit (from the original project) to this via an ESPHOME connected board. Will start looking at the code, however when telnet'ing to the device I get the following.

(Is there a correct polarity for the vbus to be connected...I receive data on both but differing output)

fprowse-a01:Downloads fprowse$ telnet 192.168.0.141 1234
Trying 192.168.0.141...
Connected to 192.168.0.141.
Escape character is '^]'.
~~	Q8"s
   
     iii�{B
v
   u
sQ
   s
~~  qQ8"{B �{B	Q8"s
   
     iii�{B
v
   u
sQ
   s
~~  qQ8"{B �{B	Q8"s
   
     iii�{B
v
   u
sQ

**Comment by oxan** [comment]
I'm not sure what your issue is.

In general, if you get seemingly-garbage output from telnet, that either means that the protocol the connected device is speaking is binary, or that the [UART settings](https://esphome.io/components/uart.html#configuration-variables) you're using are different from the connected device.

I don't know what vBUS2TTY is and I don't get any hits for it on Google, so I can't help you with that (and this isn't the place for that anyway). 

As this doesn't seem to be a problem with the stream server, I'll close this issue for now, freel free to reopen it if you discover a concrete problem.
